### ISSUE TITLE
Too many connections 

### ISSUE THREAD

**Issue by RizkyRajitha** [mikecao/umami#87]
i am getting `too many connections ` error when when loading the dashboard

i am using a` heroku postgres `db which can take up to `20` connections concurrently .

![toomany connectons](https://user-images.githubusercontent.com/38534289/91815594-6689c600-ec52-11ea-8b7e-917ae85c671e.PNG)

![heroku](https://user-images.githubusercontent.com/38534289/91819433-77870700-ec53-11ea-83bc-b4b3f35c2838.PNG)

is there a way to overcome this issue

**Comment by axelekwall** [comment]
Have you tried to add `?connection_limit=20` to the `DATABASE_URL`? Umami uses [prisma](https://www.prisma.io/) to handle the connection with the database and according to their [documentation ](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/connection-management#connection-pool)this is the way to specify the maximum number of connections.

**Comment by RizkyRajitha** [comment]
thanks for reply @axelekwall . 
i will check that and update.

**Comment by ShubhamVerma1811** [comment]
Hey @axelekwall ,

Even I am facing the same issue.
When logging it shows error 502 and I even can't access my heroku postgress database through CLI.

It says Fatal error to many connections for user.

Can you look into it?

Is this only a Heroku issue?

**Comment by axelekwall** [comment]
@ShubhamVerma1811 Have you tried specifying the maximum number of collection like I described in my earlier reply?

**Comment by ShubhamVerma1811** [comment]
> 
> 
> @ShubhamVerma1811 Have you tried specifying the maximum number of collection like I described in my earlier reply?

Yes, I set the connection_limit to 5.
But I am not sure what happened by changing that because in Heroku it still shows 20/20 connections and even shows fatal error while trying to access psql from Heroku CLI

**Comment by axelekwall** [comment]
Ok, maybe that's not a fix then. I'll let you know if I find a solution!

**Comment by hugomd** [comment]
If there are too many connections, as indicated by the error, you should try setting the connection limit to 1.

**Comment by ShubhamVerma1811** [comment]
> 
> 
> If there are too many connections, as indicated by the error, you should try setting the connection limit to 1.

But the point is I set it to 5 and it still used 20 out of 20.
So the limit didn't work right?

**Comment by hugomd** [comment]
It looks like this has been raised a few times against Prisma ([here](https://github.com/prisma/prisma/issues/942), [here](https://github.com/prisma/prisma/issues/567), and [here](https://github.com/prisma/prisma-client-js/issues/289)) and it looks like the solution is just appending the `connection_limit`.

It could also be that your Postgres server hasn't dropped the other connections..

**Comment by RizkyRajitha** [comment]
is there a way we can disconnect the connection after the query is executed .  i think because of the serverless functions it uses a new connection for every new request .

https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/connection-management#calling-disconnect-explicitly

**Comment by RizkyRajitha** [comment]
> If there are too many connections, as indicated by the error, you should try setting the connection limit to 1.

i used `connection_limit=1`  but still same

**Comment by mikecao** [comment]
Setting `connection_limit=1` is the suggested solution for prisma. Although you will need to restart your database or flush the other existing connections first. Prisma is able to disconnect after a query, but there was a bug that caused it to crash. I will check if it is resolved and if it is, re-implement the disconnect.

**Comment by mikecao** [comment]
Looks like a new version of Prisma was released yesterday with the disconnect fix, https://github.com/prisma/prisma/releases/tag/2.6.0. 🥳 

I'll test it out and see how it goes.

**Comment by mikecao** [comment]
Looks like it's still causing errors even with the latest version. 👎 

Another thing you can try is to set `idle_in_transaction_session_timeout` to have postgresql automatically flush idle connections.

**Comment by RizkyRajitha** [comment]
> Looks like it's still causing errors even with the latest version. 👎
> 
> Another thing you can try is to set `idle_in_transaction_session_timeout` to have postgresql automatically flush idle connections.
i'll take a look and let you know

thanks ✌

**Comment by mikecao** [comment]
I filed a bug with the Prisma repo regarding disconnects. You can follow here https://github.com/prisma/prisma/issues/3522

**Comment by ShubhamVerma1811** [comment]
> I filed a bug with the Prisma repo regarding disconnects. You can follow here https://github.com/prisma/prisma/issues/3522

I think this bug is fixed because the issue is closed.
Can you now try to fix this bug?

**Comment by mikecao** [comment]
@ShubhamVerma1811 The issue is closed but there hasn't been a new release of prisma yet. Will update as soon as it's out.

**Comment by mikecao** [comment]
Try the latest release and see if it helps.

**Comment by HassanCorrigan** [comment]
Still get the 'too many connections' error on the latest version. Tried using the connection_limit=1 query string and its the same.

**Comment by acoard** [comment]
I was able to replicate the issue by running the following command and can confirm it's still happening.

```bash
npm run loadtest:medium # Takes 60 seconds to run, be patient
npm run loadtest:medium -- --verbose  # Optional, see every request logged
```

I'm unsure if the issue is intermittent as wasn't looking too closely, but it at least happened  >50% of the time.

**Comment by mikecao** [comment]
The core of the issue is prisma is not disconnecting properly, even with the latest version. They fixed it from throwing errors but issue still remains. On top of that, some users have seen degraded performance from the disconnect code. I may have to explore using a different library.

**Comment by mikecao** [comment]
Closing this. Can continue discussion in #263
